### ISSUE TITLE
Failure to delete more than one person when managing permissions

### ISSUE THREAD

**Issue by TylerNakamura** [UHMDCmd/DCmd#1]
When managing permissions, if I try to use the trash icon to delete more than one person, it fails.  Please be sure to test in a test environment.

**Comment by TylerNakamura** [comment]
Originally submitted by [Michael](https://github.com/mhodges2)

**Comment by aaronvil** [comment]
Could not recreate problem to see where the error occurs

close

**Comment by aaronvil** [comment]
close

**Comment by aaronvil** [comment]
df

**Comment by TylerNakamura** [comment]
Aaron and Michael found that the issue could not be replicated. We are closing the issue.
