### ISSUE TITLE
Hosts Attribute last time a host was scanned for sec vulnerabilities

### ISSUE THREAD

**Issue by TylerNakamura** [UHMDCmd/DCmd#11]
Provide the ITS InfoSec group with a Hosts attribute that indicates the last time a host was scanned for security vulnerabilities; determine if a second "results" attribute is needed.

**Comment by aaronvil** [comment]
https://github.com/UHMDCmd/DCmd/commit/1c26bb5a7550ce8dd622bd12830a9a257219a191
