### ISSUE TITLE
DCmd Search Feature update - decals and serial numbers

### ISSUE THREAD

**Issue by TylerNakamura** [UHMDCmd/DCmd#12]
DCmd search feature should also look for decals and serial numbers; will be very helpful for inventory

**Comment by aaronvil** [comment]
Updated quicksearch code and updated github

**Comment by mhodgesatuh** [comment]
Ready for deployment to Production.

Let's keep issues open until they are deployed to production.

**Comment by aaronvil** [comment]
https://github.com/UHMDCmd/DCmd/commit/303c5f425b8e42c80e01658e90841c1a0e6447cf
