### ISSUE TITLE
Modify the DCmd Support Role Change Report to use a LISTSERV mailing list

### ISSUE THREAD

**Issue by mhodgesatuh** [UHMDCmd/DCmd#13]
The emails currently go to individuals.  Externalize control by referencing a mailing list instead.

**Comment by mhodgesatuh** [comment]
dcmd-role-change-report@lists.hawaii.edu is now ready for use.

**Comment by mhodgesatuh** [comment]
Membership in the dcmd role change report LISTSERV list is managed with the [UH Grouping](http://www.hawaii.edu/its/uhgrouping) named dcmd-role-change-report.

Edit the file /home/dcmd/dcmdConfig/reportemails.txt to reference the LISTSERV list(s) required for report distribution.

**Comment by TylerNakamura** [comment]
how is this going? any obstacles?

**Comment by mhodgesatuh** [comment]
Going well.  I discovered that the mailing list doesn't automatically send
the email; it await approval.  I'll fix that today.

**Comment by mhodgesatuh** [comment]
Initial testing revealed that the UH Grouper generated LISTSERV list required moderator approval for email messages.  Once that requirement was removed, DCmd now emails the report as expected.  Note that UH Groupings only references UH Usernames, not other LISTSERV lists.
