### ISSUE TITLE
Problematic Python Script

### ISSUE THREAD

**Issue by TylerNakamura** [UHMDCmd/DCmd#4]
Simple script in python calling on DCmd API, not behaving correctly, you can find the script here:

https://github.com/UHMDCmd/DCmd/blob/master/api/dcmd_get_primary.py

**Comment by aaronvil** [comment]
Got a working version of the script that works, ensuring that the DCmd API is working correctly. Example of the script can be found here.
[example code](https://www.hawaii.edu/bwiki/display/SITARd/Example+DCmd+API+script)
